spring:
  application:
    name: spring-ai-openai
  datasource:
    url: jdbc:postgresql://localhost:5434/vectordb
    username: vector-admin
    password: vector-admin
  ai:
    chat:
      client:
        enabled: false
        observations:
          log-prompt: true
    deepseek:
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat


    openai:
      api-key: ${GPT_API_KEY_FREE}
      chat:
        options:
          model: gpt-4o-mini
#          model: gpt-4o
      base-url: https://api.chatanywhere.tech
      embedding:
#        base-url: https://api.chatanywhere.tech
#        embeddings-path: /v1/embeddings
#        api-key: ${GPT_API_KEY_FREE}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        embeddings-path: /v1/embeddings
        api-key: ${ALY_API_KEY}
        options:
          model: text-embedding-v3
          dimensions: 512


    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
#        dimensions: 1536
#        table-name: vector_store
        dimensions: 512
        table-name: aly_vector_store
        max-document-batch-size: 10000
    mcp:
      client:
        stdio:
          connections:
            filesystem:
#              command: npx
              command: cmd.exe
              args:
                - /c
                - npx
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "./"


logging:
  level:
    root: info
    org.springframework.ai: debug
    org.springframework.web.client.RestClient: DEBUG