spring:
  application:
    name: deepseek-exploration
  http:
    client:
      factory: http_components


langchain4j:
  open-ai:
    chat-model:
#      api-key: demo
#      base-url: http://langchain4j.dev/demo/openai/v1
#      model-name: gpt-4o-mini
      api-key: ${DS_API_KEY}
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      temperature: 1.0
      top-p: 0.8
      max-tokens: 500
      timeout: 60s
      #      response-format: json_object
      response-format: json_schema
      strict-json-schema: true
      log-requests: true
      log-responses: true
      strict-tools: true

