spring:
  application:
    name: openai-explore

#langchain4j:
#  open-ai:
#    chat-model:
#      api-key: ${DS_API_KEY}
#      base-url: https://api.deepseek.com
#      log-requests: true
#      log-responses: true
#      response-format: json_object
#      model-name: deepseek-chat
#      temperature: 1.3
#      top-p: 2
#      max-tokens: 1000
#      timeout: 60s
