spring:
  application:
    name: deepseek-exploration

langchain4j:
  open-ai:
    chat-model:
      api-key: ${DS_API_KEY}
        #      api-key: demo
      base-url: https://api.deepseek.com
      #      base-url: http://langchain4j.dev/demo/openai/v1
      model-name: deepseek-chat
#      model-name: deepseek-reasoner
      temperature: 1.3
      top-p: 0.8
      max-tokens: 1000
      timeout: 60s
      #      response-format: json_object
      response-format: json_schema
      strict-json-schema: true
      log-requests: true
      log-responses: true
      strict-tools: true

